=== rdtecnologia/rotativo/assets/config/cities/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "city": {
      "type": "string"
    },
    "domain": {
      "type": "string"
    },
    "latitude": {
      "type": "number"
    },
    "longitude": {
      "type": "number"
    },
    "downloadLink": {
      "type": "string"
    },
    "termsLink": {
      "type": "string"
    },
    "androidPackage": {
      "type": "string"
    },
    "iosPackage": {
      "type": "string"
    },
    "whatsapp": {
      "type": "string"
    },
    "chatBotURL": {
      "type": "string"
    },
    "products": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        },
        {
          "type": "integer"
        }
      ]
    },
    "vehicleTypes": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        },
        {
          "type": "integer"
        }
      ]
    },
    "mainLogo": {
      "type": "string"
    },
    "logoMenu": {
      "type": "string"
    },
    "balance": {
      "type": "object",
      "properties": {
        "showBy": {
          "type": "string"
        },
        "showDetails": {
          "type": "boolean"
        }
      },
      "required": [
        "showBy",
        "showDetails"
      ]
    },
    "parkingRulesText": {
      "type": "string"
    },
    "parkingRules": {
      "type": "object",
      "properties": {
        "1": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            },
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            },
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            }
          ]
        },
        "2": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            },
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            },
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            }
          ]
        }
      },
      "required": [
        "1"
      ]
    },
    "purchase": {
      "type": "object",
      "properties": {
        "vehicleTypeDefault": {
          "type": "integer"
        },
        "showBy": {
          "type": "string"
        },
        "chargeback": {
          "type": "boolean"
        },
        "minCreditsByVehicle": {
          "type": "object",
          "properties": {
            "1": {
              "type": "integer"
            },
            "2": {
              "type": "integer"
            }
          },
          "required": [
            "1"
          ]
        },
        "products": {
          "type": "object",
          "properties": {
            "1": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                }
              ]
            },
            "2": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                }
              ]
            }
          },
          "required": [
            "1"
          ]
        },
        "payment": {
          "type": "object",
          "properties": {
            "creditCard": {
              "type": "boolean"
            },
            "billet": {
              "type": "boolean"
            },
            "pix": {
              "type": "boolean"
            }
          },
          "required": [
            "creditCard",
            "billet"
          ]
        }
      },
      "required": [
        "vehicleTypeDefault",
        "showBy",
        "chargeback",
        "minCreditsByVehicle",
        "products",
        "payment"
      ]
    },
    "faq": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        }
      ]
    }
  },
  "required": [
    "city",
    "domain",
    "latitude",
    "longitude",
    "downloadLink",
    "androidPackage",
    "iosPackage",
    "products",
    "vehicleTypes",
    "mainLogo",
    "logoMenu",
    "balance",
    "parkingRules",
    "purchase",
    "faq"
  ]
}

=== rdtecnologia/rotativo/assets/config/cities/RibeiraoDasNeves/RibeiraoDasNeves.json
{
  "$schema": "../schema.json",
  "city": "Ribeirão das Neves",
  "domain": "Ribeirao das Neves",
  "latitude": -19.7745768,
  "longitude": -44.0860605,
  "downloadLink": "http://www.rotativodigital.com.br/app/?city=neves",
  "termsLink": "http://www.rotativodigital.com.br/wp-content/uploads/2021/10/termos-de-uso-ribeirao-das-neves.pdf",
  "androidPackage": "com.rotativodigitalneves",
  "iosPackage": "com.rotativodigitalneves",
  "products": [7],
  "vehicleTypes": [1],
  "mainLogo": "",
  "logoMenu": "",
  "balance": {
    "showBy": "real",
    "showDetails": false
  },
  "parkingRules": {
    "1": [
      {"time": 60, "price": 2, "credits": 1},
      {"time": 120, "price": 2, "credits": 1},
      {"time": 240, "price": 2, "credits": 1}
    ]
  },
  "parkingRulesText": "O valor de cada crédito para estacionamento rotativo é de R$2,00. O tempo máximo de duração de cada crédito é o tempo de permanência informado na placa de sinalização, próximo ao local do veículo estacionado.",
  "purchase": {
    "vehicleTypeDefault": 1,
    "showBy": "credits",
    "chargeback": true,
    "minCreditsByVehicle": {
      "1": 1
    },
    "products": {
      "1": [
        {
          "credits": 5,
          "price": 10
        },
        {
          "credits": 10,
          "price": 20
        },
        {
          "credits": 15,
          "price": 30
        },
        {
          "credits": 25,
          "price": 50
        }
      ]
    },
    "payment": {
      "creditCard": true,
      "billet": true
    }
  },
  "faq": [
    {
      "title": "O que é o Rotativo Digital Neves?",
      "content": "O Sistema de estacionamento Rotativo tem como objetivo, aumentar a oferta de vagas nas regiões de grande concentração de comércio, serviços e lazer, oferecendo aos motoristas mais facilidade de estacionamento, contribuindo para melhorar a qualidade de vida, assim como proporcionar o aumento da fluidez do trânsito.\n\nA receita líquida obtida com o pagamento das vagas, é revertida para projetos de melhoria do sistema viário da cidade.\n\nEm RIBEIRÃO DAS NEVES, a Secretaria Municipal De Segurança, Trânsito E Transporte Departamento de Trânsito – SMSTT é o órgão responsável pelo gerenciamento do Estacionamento ROTATIVO DIGITAL NEVES. Com os Decretos Municipais nº. 59 de 8 de maio de 2.017 e nº. 117 de 21 de junho de 2018, e através da Concorrência Pública nº 002/2018, onde a empresa Ti.Mob – Tecnologia e Soluções de Mobilidade, sagrou-se vencedora do certame como empresa especializada para execução dos serviços de Gestão, comercialização de Créditos Eletrônicos e equipamentos para fiscalização."
    },
    {
      "title": "Como funciona o Rotativo Digital",
      "content": "O sistema ROTATIVO DIGITAL NEVES é um sistema moderno, que tem como objetivo proporcionar conforto, praticidade e uma série de vantagens para a população de sua cidade.\n\nPara utilização do sistema estacionamento ROTATIVO DIGITAL NEVES, o usuário deverá possuir CRÉDITOS ELETRÔNICOS ATIVOS para a vaga em que está estacionado.\n\nPara maior comodidade e conforto da população foram disponibilizadas 02 formas de utilização dos créditos:\na) compra/ativação de CRÉDITO ELETRÔNICO AVULSO para usuários que fizerem uso do estacionamento pontualmente;\nb) compra de CRÉDITOS PRÉ-PAGOS, onde os usuários que forem recorrentes podem optar por se cadastrar no sistema e comprar uma maior quantidade de créditos, e ativar somente quando for utilizar a vaga de estacionamento rotativo.\n\nA Ti.Mob também disponibiliza aos USUÁRIOS do ROTATIVO DIGITAL NEVES aplicativo “ROTATIVO DIGITAL NEVES” (disponível nas lojas de aplicativos Google Play e Apple Store), além do site: www.rotativodigital.com.br/ribeirao-das-neves.\n\nAo estacionar em uma das vagas de estacionamento ROTATIVO DIGITAL NEVES, o usuário deverá ATIVAR créditos de estacionamento."
    },
    {
      "title": "Valor e tempo do estacionamento",
      "content": "O valor de cada crédito de estacionamento no ROTATIVO DIGITAL NEVES é de R$ 2,00 (dois reais) válidos por permanência conforme a área de estacionamento, que poderá variar entre 1, 2 ou 4 horas. Ao estacionar, verifique a placa de regulamentação com o tempo permitido para este local."
    },
    {
      "title": "Horário de funcionamento",
      "content": "O sistema de Estacionamento Rotativo de RIBEIRÃO DAS NEVES funciona de segunda à  sexta feira de 8 às 18 horas e aos  sábado das 8h às 13horas. Domingos e feriados não há cobrança. "
    },
    {
      "title": "Como funciona a fiscalização",
      "content": "Os Agentes de Trânsito de RIBEIRÃO DAS NEVES fazem a fiscalização através de sistema disponível em seus equipamentos smartphones, bem como através de um veículo de videomonitoramento. A consulta é realizada pela placa do veículo. Caso detectado que o veículo está estacionado de forma irregular, será automaticamente autuado. Em alguns casos, poderá ocorrer a remoção do veículo. "
    },
    {
      "title": "Quantidade de veículos cadastrados em um mesmo CPF",
      "content": "Você pode ter até cinco veículos cadastrados em seu CPF. "
    },
    {
      "title": "Vagas especiais",
      "content": "O uso da Credencial de Estacionamento Especial para Idosos e portadores de necessidades especiais é obrigatório em todas as vagas reservadas, localizadas ou não em áreas de estacionamento rotativo.\n\nO usuário destas vagas, deverá fazer o pagamento do valor de estacionamento, assim como os demais usuários nas vagas de uso comum."
    },
    {
      "title": "Onde posso comprar e ativar os meus créditos?",
      "content": "Os CRÉDITOS ELETRÔNICOS podem ser adquiridos através de Pontos de venda espalhados pela cidade nas áreas do Estacionamento Rotativo ou através do aplicativo ROTATIVO DIGITAL NEVES, é rápido, fácil e seguro."
    },
    {
      "title": "Vendi/troquei meu veículo, como faço para transferir os créditos que possuia para o novo veículo?",
      "content": "Por medida de segurança e para que se evite fraudes, seus CRÉDITOS ELETRÔNICOS adquiridos são vinculados ao seu CPF como usuário, e não às Placas de seus veículos. Nesse caso, basta que o veículo transferido seja retirado e o novo veículo seja cadastrado. Daí a necessidade do condutor informar seu CPF ao cadastrar como usuário do estacionamento rotativo.  "
    }
  ]
}

=== rdtecnologia/rotativo/assets/config/cities/OuroPreto/OuroPreto.json
{
  "$schema": "../schema.json",
  "city": "Ouro Preto",
  "domain": "Ouro Preto",
  "latitude": -20.3875396,
  "longitude": -43.5097469,
  "downloadLink": "http://www.rotativodigital.com.br/app/?city=ouropreto",
  "termsLink": "http://www.rotativodigital.com.br/wp-content/uploads/2024/01/termos-de-uso-rotativo-ouro-preto.pdf",
  "androidPackage": "com.rotativodigitalouropretord",
  "iosPackage": "com.rotativodigitalouropretord",
  "whatsapp": "(31) 99835-9953",
  "chatBotURL": "https://timob.chat.blip.ai/?appKey=YXRlbmRpbWVudG9odW1hbm9hcHBvcDozN2JjMDc0Mi1hN2Q1LTQyZTItYTcxZS1lNzg0ZWY4ZjNhNDY=",
  "products": [13],
  "vehicleTypes": [1, 2],
  "mainLogo": "",
  "logoMenu": "",
  "balance": {
    "showBy": "real",
    "showDetails": false
  },
  "parkingRules": {
    "1": [
      {"time": 60, "price": 2, "credits": 4},
      {"time": 120, "price": 3.5, "credits": 7},
      {"time": 180, "price": 5, "credits": 10}
    ],
    "2": [{"time": 60, "price": 1, "credits": 2}]
  },
  "purchase": {
    "vehicleTypeDefault": 1,
    "showBy": "real",
    "chargeback": true,
    "minCreditsByVehicle": {
      "1": 2,
      "2": 2
    },
    "products": {
      "1": [
        {
          "credits": 30,
          "price": 15
        },
        {
          "credits": 40,
          "price": 20
        },
        {
          "credits": 60,
          "price": 30
        },
        {
          "credits": 90,
          "price": 45
        },
        {
          "credits": 100,
          "price": 50
        },
        {
          "credits": 200,
          "price": 100
        }
      ],
      "2": [
        {
          "credits": 30,
          "price": 15
        },
        {
          "credits": 40,
          "price": 20
        },
        {
          "credits": 60,
          "price": 30
        },
        {
          "credits": 90,
          "price": 45
        },
        {
          "credits": 100,
          "price": 50
        },
        {
          "credits": 200,
          "price": 100
        }
      ]
    },
    "payment": {
      "creditCard": true,
      "billet": true,
      "pix": true
    }
  },
  "faq": [
    {
      "title": "O que é o Rotativo Digital Ouro Preto?",
      "content": "O sistema de estacionamento Rotativo Digital de Ouro Preto tem como objetivo, aumentar a oferta de vagas de estacionamento nas regiões de grande concentração de comércio e lazer, oferecendo aos motoristas mais facilidade de estacionamento, contribuindo para melhorar a qualidade de vida, assim como proporcionar o aumento da fluidez do trânsito.\n\nA receita líquida obtida com o pagamento para a utilização das vagas, é revertida para projetos de melhoria do sistema viário da cidade.\n\nEm Ouro Preto a SECRETARIA MUNICIPAL DE SEGURANÇA E TRÂNSITO, através da OUROTRAN - Departamento Municipal de Trânsito de Ouro Preto é quem é o órgão responsável pela gestão e gerenciamento do ROTATIVO DIGITAL na cidade.\n\nLEGISLAÇÃO APLICÁVEL: Decreto Municipal nº. 4.893/2017; Decreto Municipal nº 3.964/2014; Lei Federal nº 10.520/2002; Lei Complementar Federal nº 123/2006 e Lei Federal nº 8.666/1993."
    },
    {
      "title": "Como funciona o Rotativo Digital Ouro Preto?",
      "content": "O sistema Rotativo Digital Ouro Preto é um sistema moderno, que tem como maior propósito proporcionar conforto, praticidade e uma série de vantagens para a população de Ouro Preto e seus visitantes.\n\nPara utilização do sistema de estacionamento Rotativo Digital Ouro Preto, o usuário deverá adquirir CRÉDITOS ELETRÔNICOS e ao estacionar seu veículo em uma das vagas identificadas como Estacionamento Rotativo, ativar seus créditos.\n\nO tempo máximo de permanência na vaga é o informado na placa de sinalização local.\n\nPara maior comodidade e conforto dos usuários, foram disponibilizadas 02 formas de aquisição dos créditos: a) CRÉDITO ELETRÔNICO AVULSO: ideal para o usuário que irá fazer a utilização pontual da vaga de estacionamento. Neste modelo o usuário compra/ativa 01 crédito sob demanda.\n\n b) CRÉDITO ELETRÔNICO PRÉ-PAGO: os usuários recorrentes, poderão adquirir quantidades maiores de CRÉDITOS ELETRÔNICOS que serão armazenados em uma conta, vinculada ao CPF de cadastro do usuário. Neste modelo o usuário poderá comprar/armazenar saldo de créditos em sua conta, podendo com comodidade ATIVÁ-LOS quando for estacionar seu veículo em uma das vagas do Rotativo Digital."
    },
    {
      "title": "Valor e tempo do estacionamento",
      "content": "O sistema Rotativo Digital Ouro Preto possui vagas exclusivas para o estacionamento de Veículos de 02 rodas (motocicletas) e veículos de 04 rodas (carros). \n\nMOTOCICLETAS\n1 HORA = R$ 1,00 (um real)\n\nCARROS\n1 HORA = R$ 2,00 (dois reais)\n2 HORAS = R$ 3,50 (três reais e cinquenta centavos)\n3 HORAS = R$ 5,00 (cinco reais)\n\nAo estacionar seu veículo (carro ou moto) o USUÁRIO deverá ATIVAR seus créditos eletrônicos de acordo com o tempo máximo informado na PLACA DE SINALIZAÇÃO."
    },
    {
      "title": "Horário de funcionamento",
      "content": "O horário de funcionamento do Sistema ZONA AZUL OURO PRETO será: \n\na) Segunda feira a Sábado - das 08:00 horas às 18:00 horas \nb) Domingos e feriados - de 08:00 horas às 13:00 horas\n\nO tempo máximo de permanência será de até 03 (três) horas, conforme regulamentação.\n\nO estacionamento será livre de segunda feira a sábado após às 18:00 horas, e aos domingos e feriados após às 13:00 horas."
    },
    {
      "title": "Onde posso comprar e ativar os meus créditos?",
      "content": "Visando maior disponibilidade, comodidade e conveniência aos USUÁRIOS, os créditos poderão ser comprados e ativados em diversos canais:\n\na) PONTOS DE VENDA CREDENCIADOS -  comércios locais credenciados como padarias, bancas de revista, farmácias, lanchonetes, lojas, etc., possuem máquinas para a venda/ativação de créditos eletrônicos avulso e/ou pré-pago.\n\nb) APLICATIVO / WEB SITE ROTATIVO DIGITAL OURO PRETO.  \n\n c).  WHATAPP ROTATIVO DIGITAL OURO PRETO – através do n° (31) 9 9835-9953"
    },
    {
      "title": "Como funciona a FISCALIZAÇÃO?",
      "content": "Os AGENTES DE TRÂNSITO da OUROTRAN e a Guarda Municipal de Ouro Preto fazem a fiscalização diária da utilização das vagas na cidade de Ouro Preto.\n\nEsta fiscalização pode ocorrer de 02 formas:\n\na). Manualmente: Através de tablets/smartphones equipados com o sistema de fiscalização Rotativo Digital os agentes de trânsito ou os guardas municipais consultam as placas de veículos estacionados nas vagas de estacionamento rotativo da cidade.\n\nb). Videomonitoramento: veículos da OUROTRAN e da Guarda Municipal estão equipados com câmeras de videomonitoramento interligados ao sistema de fiscalização Rotativo Digital. Quando em rota, as câmeras de videomonitoramento automaticamente detectam as placas de veículos estacionados, consultando se possuem créditos válidos para estacionamento. \n\nEstando o veículo estacionado sem créditos ativos ou vencidos, automaticamente é gerado a informação no sistema de fiscalização, devendo o agente de trânsito/guarda municipal proceder com a autuação do veículo.  "
    },
    {
      "title": "Vagas especiais",
      "content": "Conforme a Lei Federal 10741/03 e a Lei Federal nº 10.098 Idosos e PNE - Portadores de Necessidades Especiais, terão direito a vagas especiais de estacionamento. \n\nA utilização das vagas pelos Idosos e PNE - Portadores de Necessidades Especiais, deverá ser feito nas vagas destinadas e sinalizadas aos mesmos, devendo os mesmos utilizar a CREDENCIAL especial de estacionamento, que deverá estar exposta em local visível no painel frontal do veículo. "
    }
  ]
}
