=== rdtecnologia/rotativo/assets/config/cities/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "city": {
      "type": "string"
    },
    "domain": {
      "type": "string"
    },
    "latitude": {
      "type": "number"
    },
    "longitude": {
      "type": "number"
    },
    "downloadLink": {
      "type": "string"
    },
    "termsLink": {
      "type": "string"
    },
    "androidPackage": {
      "type": "string"
    },
    "iosPackage": {
      "type": "string"
    },
    "whatsapp": {
      "type": "string"
    },
    "chatBotURL": {
      "type": "string"
    },
    "products": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        },
        {
          "type": "integer"
        }
      ]
    },
    "vehicleTypes": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        },
        {
          "type": "integer"
        }
      ]
    },
    "mainLogo": {
      "type": "string"
    },
    "logoMenu": {
      "type": "string"
    },
    "balance": {
      "type": "object",
      "properties": {
        "showBy": {
          "type": "string"
        },
        "showDetails": {
          "type": "boolean"
        }
      },
      "required": [
        "showBy",
        "showDetails"
      ]
    },
    "parkingRulesText": {
      "type": "string"
    },
    "parkingRules": {
      "type": "object",
      "properties": {
        "1": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            },
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            },
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            }
          ]
        },
        "2": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            },
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            },
            {
              "type": "object",
              "properties": {
                "time": {
                  "type": "integer"
                },
                "price": {
                  "type": "number"
                },
                "credits": {
                  "type": "integer"
                },
                "area": {
                  "type": "string"
                },
                "color": {
                  "type": "string"
                }
              },
              "required": [
                "time",
                "price",
                "credits",
                "area"
              ]
            }
          ]
        }
      },
      "required": [
        "1"
      ]
    },
    "purchase": {
      "type": "object",
      "properties": {
        "vehicleTypeDefault": {
          "type": "integer"
        },
        "showBy": {
          "type": "string"
        },
        "chargeback": {
          "type": "boolean"
        },
        "minCreditsByVehicle": {
          "type": "object",
          "properties": {
            "1": {
              "type": "integer"
            },
            "2": {
              "type": "integer"
            }
          },
          "required": [
            "1"
          ]
        },
        "products": {
          "type": "object",
          "properties": {
            "1": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                }
              ]
            },
            "2": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "credits": {
                      "type": "integer"
                    },
                    "price": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "credits",
                    "price"
                  ]
                }
              ]
            }
          },
          "required": [
            "1"
          ]
        },
        "payment": {
          "type": "object",
          "properties": {
            "creditCard": {
              "type": "boolean"
            },
            "billet": {
              "type": "boolean"
            },
            "pix": {
              "type": "boolean"
            }
          },
          "required": [
            "creditCard",
            "billet"
          ]
        }
      },
      "required": [
        "vehicleTypeDefault",
        "showBy",
        "chargeback",
        "minCreditsByVehicle",
        "products",
        "payment"
      ]
    },
    "faq": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "content"
          ]
        }
      ]
    }
  },
  "required": [
    "city",
    "domain",
    "latitude",
    "longitude",
    "downloadLink",
    "androidPackage",
    "iosPackage",
    "products",
    "vehicleTypes",
    "mainLogo",
    "logoMenu",
    "balance",
    "parkingRules",
    "purchase",
    "faq"
  ]
}

=== rdtecnologia/rotativo/cities_old/config/cities/Igarape/Igarape.json
{
  "$schema": "../schema.json",
  "city": "Igarapé",
  "domain": "Igarape",
  "latitude": -20.0704606,
  "longitude": -44.3071211,
  "downloadLink": "http://www.rotativodigital.com.br/app/?city=igarape",
  "termsLink": "http://www.areaazuligarape.com.br/wp-content/uploads/2019/10/SITE-TERMOS-DE-USO-IGARAP%C3%89.pdf",
  "androidPackage": "com.rotativodigitaligarape",
  "iosPackage": "com.rotativodigitaligarape",
  "products": [13],
  "vehicleTypes": [1, 2],
  "mainLogo": "logo-rotativo-digital-small_b_igarape.png",
  "logoMenu": "logo-erotativo-digital-small_b_igarape",
  "balance": {
    "showBy": "real",
    "showDetails": false
  },
  "parkingRules": {
    "1": [
      {"time": 30, "price": 1, "credits": 2},
      {"time": 60, "price": 1.5, "credits": 3},
      {"time": 120, "price": 2, "credits": 4}
    ],
    "2": [
      {"time": 30, "price": 0.5, "credits": 1},
      {"time": 60, "price": 1, "credits": 2},
      {"time": 120, "price": 1.5, "credits": 3}
    ]
  },
  "purchase": {
    "vehicleTypeDefault": 1,
    "showBy": "real",
    "chargeback": true,
    "minCreditsByVehicle": {
      "1": 30,
      "2": 10
    },
    "products": {
      "1": [
        {
          "credits": 30,
          "price": 15
        },
        {
          "credits": 40,
          "price": 20
        },
        {
          "credits": 60,
          "price": 30
        },
        {
          "credits": 90,
          "price": 45
        },
        {
          "credits": 100,
          "price": 50
        },
        {
          "credits": 200,
          "price": 100
        }
      ],
      "2": [
        {
          "credits": 30,
          "price": 15
        },
        {
          "credits": 40,
          "price": 20
        },
        {
          "credits": 60,
          "price": 30
        },
        {
          "credits": 90,
          "price": 45
        },
        {
          "credits": 100,
          "price": 50
        },
        {
          "credits": 200,
          "price": 100
        }
      ]
    },
    "payment": {
      "creditCard": true,
      "billet": true
    }
  },
  "faq": [
    {
      "title": "O que é o Área Azul Igarapé?",
      "content": "O Sistema de estacionamento Rotativo tem como objetivo, aumentar a oferta de vagas nas regiões de grande concentração de comércio, serviços e lazer, oferecendo aos motoristas mais facilidade de estacionamento, contribuindo para melhorar a qualidade de vida, assim como proporcionar o aumento da fluidez do trânsito. \n\nA receita líquida obtida com o pagamento das vagas, é revertida para projetos de melhoria do sistema viário da cidade. \n\nEm Igarapé, o Departamento de Trânsito - IGARATRANS é o órgão responsável pelo gerenciamento do Estacionamento Rotativo ÁREA AZUL IGARAPÉ. Através do Chamamento Público nº 012/2019, Processo Administrativo nº 033/2019, Lei Municipal nº 1.737 de 25 de abril de 2017, no Decreto Municipal nº. 2.265 de 16 de agosto de 2.019, sendo a Ti.Mob – Tecnologia e Soluções de Mobilidade, credenciada como empresa especializada para execução de Serviços de Locação Mensal de Software de Gestão e equipamentos para Fiscalização, comercialização de Créditos Eletrônicos conforme previsto no Anexo I do Edital.  "
    },
    {
      "title": "Como funciona o Rotativo Digital",
      "content": "O sistema ÁREA AZUL IGARAPÉ é um sistema moderno, que tem como objetivo proporcionar conforto, praticidade e uma série de vantagens para a população de sua cidade. \n\nPara utilização do sistema estacionamento ÁREA AZUL IGARAPÉ, o usuário deverá possuir CRÉDITOS ELETRÔNICOS ATIVOS para a vaga em que está estacionado. \n\nPara maior comodidade e conforto da população foram disponibilizadas 02 formas de utilização dos créditos: \n  a) compra/ativação de CRÉDITO ELETRÔNICO AVULSO para usuários que fizerem uso do estacionamento pontualmente; \nb) compra de CRÉDITOS PRÉ-PAGOS, onde os usuários que forem recorrentes podem optar por se cadastrar no sistema e comprar uma maior quantidade de créditos, e ativar somente quando for utilizar a vaga de estacionamento rotativo. \n\nA Ti.Mob também disponibiliza aos USUÁRIOS da ÁREA AZUL IGARAPÉ o aplicativo “ÁREA AZUL IGARAPÉ” (disponível nas lojas de aplicativos Google Play e Apple Store), além do site: rotativodigital.com.br. \n\nAo estacionar em uma das vagas de estacionamento ÁREA AZUL IGARAPÉ, o usuário deverá ATIVAR créditos de estacionamento. "
    },
    {
      "title": "Valor e tempo do estacionamento",
      "content": "O valor de cada crédito de estacionamento na ÁREA AZUL IGARAPÉ é de: \n\nR$ 1,00 - 30 minutos\nR$ 1,50 - 01 hora\nR$2,00 - 02 horas"
    },
    {
      "title": "Horário de funcionamento",
      "content": "O sistema de Estacionamento Rotativo de Itararé funciona de segunda à sexta-feira das 9h às 17h e aos sábados das 9h às 14h. \n\nAos domingos e feriados não é necessário o uso do ÁREA AZUL IGARAPÉ. "
    },
    {
      "title": "Como funciona a fiscalização",
      "content": "Os Agentes de Trânsito de IGARAPÉ fazem a fiscalização através de sistema disponível em seus equipamentos smartphones / tablet. A consulta é realizada pelo número da placa do veículo. Caso detectado que o veículo está estacionado de forma irregular, será automaticamente autuado. Em alguns casos, poderá ocorrer a remoção do veículo.  "
    },
    {
      "title": "Quantidade de veículos cadastrados em um mesmo CPF",
      "content": "Você pode ter vários veículos cadastrados em seu CPF. "
    },
    {
      "title": "Vagas especiais",
      "content": "O uso da Credencial de Estacionamento Especial para Idosos e portadores de necessidades especiais é obrigatório em todas as vagas reservadas, localizadas ou não em áreas de estacionamento rotativo. \n\nO usuário destas vagas, deverá fazer o pagamento do valor de estacionamento, assim como os demais usuários. "
    },
    {
      "title": "Onde posso comprar e ativar os meus créditos?",
      "content": "Os CRÉDITOS ELETRÔNICOS podem ser adquiridos através de Pontos de venda espalhados pela cidade nas áreas do Estacionamento Rotativo ou através do aplicativo ÁREA AZUL IGARAPÉ, é rápido, fácil e seguro. "
    },
    {
      "title": "Vendi/troquei meu veículo, como faço para transferir os créditos que possuia para o novo veículo?",
      "content": "Por medida de segurança e para que se evite fraudes, seus CRÉDITOS ELETRÔNICOS adquiridos são vinculados ao seu CPF como usuário e não à (s) Placa (s) de seu (s) veículo (s). Nesse caso, basta que o veículo transferido seja retirado e o novo veículo seja cadastrado. Daí a necessidade do condutor informar seu CPF ao cadastrar como usuário do estacionamento rotativo.         "
    }
  ]
}

=== rdtecnologia/rotativo/cities_old/config/cities/Janauba/Janauba.json
{
  "$schema": "../schema.json",
  "city": "Janaúba",
  "domain": "Janauba",
  "latitude": -15.798453,
  "longitude": -43.3166872,
  "downloadLink": "http://www.rotativodigital.com.br/app/?city=janauba",
  "termsLink": "http://www.rotativodigital.com.br/wp-content/uploads/2023/06/termos-de-uso-faixa-azul-janauba.pdf",
  "androidPackage": "com.rotativodigitaljanauba",
  "iosPackage": "com.rotativodigitaljanauba",
  "products": [7],
  "vehicleTypes": [1],
  "mainLogo": "logo-rotativo-digital-small_b_janauba.png",
  "logoMenu": "logo-rotativo-digital-brancoe-janauba.png",
  "balance": {
    "showBy": "real",
    "showDetails": false
  },
  "parkingRules": {
    "1": [
      {"time": 120, "price": 2, "credits": 1},
      {"time": 240, "price": 4, "credits": 2}
    ]
  },
  "purchase": {
    "vehicleTypeDefault": 1,
    "showBy": "real",
    "chargeback": true,
    "minCreditsByVehicle": {
      "1": 1
    },
    "products": {
      "1": [
        {
          "credits": 5,
          "price": 10
        },
        {
          "credits": 10,
          "price": 20
        },
        {
          "credits": 15,
          "price": 30
        },
        {
          "credits": 20,
          "price": 40
        },
        {
          "credits": 25,
          "price": 50
        },
        {
          "credits": 30,
          "price": 60
        }
      ]
    },
    "payment": {
      "creditCard": true,
      "billet": true
    }
  },
  "faq": [
    {
      "title": "O que é a Faixa Azul Janaúba",
      "content": "É o Sistema de estacionamento Rotativo que tem como objetivo, aumentar a oferta e democratizar as vagas nas regiões de grande concentração de comércio, serviços e lazer, oferecendo aos motoristas mais facilidade de estacionamento, contribuindo para melhorar a qualidade de vida, assim como proporcionar o aumento da fluidez do trânsito. A receita líquida obtida com o pagamento das vagas, é revertida para projetos de melhoria do sistema viário da cidade. Em Janaúba, o Departamento de Trânsito é o órgão responsável pelo gerenciamento do Estacionamento Rotativo FAIXA AZUL JANAÚBA. Através do Decreto Municipal nº.  37/2023, sendo a RD Tecnologia e Mobilidade, credenciada como empresa especializada para execução de Serviços de Locação Mensal de Software de Gestão e equipamentos para Fiscalização, comercialização de Créditos Eletrônicos conforme previsto no Edital."
    },
    {
      "title": "Como funciona a Faixa Azul Janaúba",
      "content": "O sistema FAIXA AZUL JANAÚBA é um sistema moderno, que tem como objetivo proporcionar conforto, praticidade e uma série de vantagens para a população de sua cidade. Para utilização do sistema estacionamento FAIXA AZUL JANAÚBA, o usuário deverá possuir CRÉDITOS ELETRÔNICOS ATIVOS para a vaga em que está estacionado. Para maior comodidade e conforto da população foram disponibilizadas 02 formas de utilização dos créditos: compra/ativação de CRÉDITO ELETRÔNICO AVULSO para usuários que fizerem uso do estacionamento pontualmente; compra de CRÉDITOS PRÉ-PAGOS, onde os usuários que forem recorrentes podem optar por se cadastrar no sistema e comprar uma maior quantidade de créditos, e ativar somente quando for utilizar a vaga de estacionamento rotativo. A RD Tecnologia  também disponibiliza aos USUÁRIOS da FAIXA AZUL JANAÚBA o aplicativo “FAIXA AZUL JANAÚBA” (disponível nas lojas de aplicativos Google Play e Apple Store), além do site: faixaazuljanauba.com.br Ao estacionar em uma das vagas de estacionamento FAIXA AZUL JANAÚBA, o usuário deverá ATIVAR créditos de estacionamento. A OBRIGAÇÃO DE ATIVAÇÃO DOS CRÉDITOS É SEMPRE RESPONSABILIDADE DO USUÁRIO."
    },
    {
      "title": "Valor do estacionamento",
      "content": "O valor de cada crédito de estacionamento na FAIXA AZUL JANAÚBA é de: \n\n R$2,00 para 02 horas \n\n R$4,00 para 4 horas"
    },
    {
      "title": "Horário de funcionamento",
      "content": "O sistema de Estacionamento Rotativo de Janaúba funciona de segunda à sexta-feira das 8h às 18h e aos sábados das 8h às 13h. Aos domingos e feriados não é necessário o uso do FAIXA AZUL JANAÚBA."
    },
    {
      "title": "Como funciona a fiscalização",
      "content": "A Polícia Militar  de JANAÚBA  faz a fiscalização através de sistema disponível em seus equipamentos smartphones. A consulta é realizada pelo número da placa do veículo. Caso detectado que o veículo está estacionado de forma irregular, será automaticamente autuado. Podendo ocorrer a remoção do veículo."
    },
    {
      "title": "Quantidade de veículos cadastrados no mesmo CPF",
      "content": "Você pode ter vários veículos cadastrados em seu CPF."
    },
    {
      "title": "Vagas especiais",
      "content": "O uso da Credencial de Estacionamento Especial para Idosos e portadores de necessidades especiais é obrigatório em todas as vagas reservadas, localizadas ou não em áreas de estacionamento rotativo. \n\n Para a utilização das vagas de idosos, além do cartão credencial é obrigatório  o pagamento da tarifa."
    },
    {
      "title": "Onde posso comprar e ativar os meus créditos?",
      "content": "Os CRÉDITOS ELETRÔNICOS podem ser adquiridos através de Pontos de venda espalhados pela cidade nas áreas do Estacionamento Rotativo, Site www.faixaazuljanauba.com.br  ou através do aplicativo FAIXA AZUL JANAÚBA, é rápido, fácil e seguro. Os pontos de venda podem ser encontrados através do WhatsApp (31) 98423-2393 e também por identificação visual (adesivo)."
    },
    {
      "title": "Vendi/troquei meu veículo, como faço para transferir os créditos que possuia para o novo veículo?",
      "content": "Por medida de segurança e para que se evite fraudes, seus CRÉDITOS ELETRÔNICOS adquiridos são vinculados ao seu CPF como usuário, e não às Placas de seus veículos. Nesse caso, basta que o veículo transferido seja retirado e o novo veículo seja cadastrado. Daí a necessidade do condutor informar seu CPF ao cadastrar como usuário do estacionamento rotativo."
    },
    {
      "title": "Funções presentes no aplicativo",
      "content": "Compra de créditos por cartão de credito e boleto bancário, através da segurança de sistemas digitais protegidos.\n\nMenu para ativação de créditos contendo todas as informações gerenciais tais como ultimas ativações, saldo disponível, e tempo de permanência restante.\n\nMenu para envio de dúvidas, sugestões de melhorias ou reclamações.\n\nObs.: Além destes recursos, a RD Tecnologia  está em constante evolução, buscando sempre melhorar no atendimento ao usuário."
    }
  ]
}
